#!/bin/bash
set -euo pipefail

# Upload artifacts to S3 with public-read ACL.
# - Uploads corkscrew-*.tar.gz to s3://wb-data-public/corkscrew/
# - Publishes a flat APT repo under s3://wb-data-public/corkscrew/apt/debs with:
#   * all .deb files from packaging/debs
#   * Packages and Packages.gz (pre-generated by build_deb.sh)
#   * public.asc (GPG public key) at s3://wb-data-public/corkscrew/apt/public.asc
# Idempotent: skips upload when the remote object matches the local file MD5.
# AWS credentials/region are loaded from .env in this directory if present.

# Resolve this script's directory (matches style used in wrapper.sh)
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

SELFDIR=$( dirname $(realpath "$0") )
SELFDIR="`cd -P \"$SELFDIR\" && pwd`"

ENV_FILE="$SELFDIR/.env"

# Load AWS_* from .env if present
if [ -f "$ENV_FILE" ]; then
  # Export variables defined in .env
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

# Map S3_* aliases to AWS_* if provided, and ensure exports
if [ -n "${S3_ACCESS_KEY_ID:-}" ] && [ -z "${AWS_ACCESS_KEY_ID:-}" ]; then
  export AWS_ACCESS_KEY_ID="$S3_ACCESS_KEY_ID"
fi
if [ -n "${S3_SECRET_ACCESS_KEY:-}" ] && [ -z "${AWS_SECRET_ACCESS_KEY:-}" ]; then
  export AWS_SECRET_ACCESS_KEY="$S3_SECRET_ACCESS_KEY"
fi
if [ -n "${S3_SESSION_TOKEN:-}" ] && [ -z "${AWS_SESSION_TOKEN:-}" ]; then
  export AWS_SESSION_TOKEN="$S3_SESSION_TOKEN"
fi
if [ -n "${S3_REGION:-}" ] && [ -z "${AWS_REGION:-}" ] && [ -z "${AWS_DEFAULT_REGION:-}" ]; then
  export AWS_REGION="$S3_REGION"
fi

# Ensure variables are exported if already set by the environment/.env
[ -n "${AWS_ACCESS_KEY_ID:-}" ] && export AWS_ACCESS_KEY_ID
[ -n "${AWS_SECRET_ACCESS_KEY:-}" ] && export AWS_SECRET_ACCESS_KEY
[ -n "${AWS_SESSION_TOKEN:-}" ] && export AWS_SESSION_TOKEN
[ -n "${AWS_PROFILE:-}" ] && export AWS_PROFILE

# Prefer AWS_REGION, fallback to AWS_DEFAULT_REGION, default to us-east-1
AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
export AWS_REGION
export AWS_DEFAULT_REGION="$AWS_REGION"

if ! command -v aws >/dev/null 2>&1; then
  echo "Error: aws CLI is required. Install via 'brew install awscli' or similar." >&2
  exit 1
fi

# Parse flags
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=true
      ;;
  esac
done

if [ "$DRY_RUN" = true ]; then
  echo "Dry run: no uploads will be performed"
fi

# Compute lowercase MD5 hex of a file, portable across macOS/Linux
md5_of_file() {
  local file="$1"
  if command -v md5sum >/dev/null 2>&1; then
    md5sum "$file" | awk '{print tolower($1)}'
  elif command -v md5 >/dev/null 2>&1; then
    md5 -q "$file" | tr '[:upper:]' '[:lower:]'
  elif command -v ruby >/dev/null 2>&1; then
    ruby -rdigest -e 'f=ARGV[0]; puts Digest::MD5.file(f).hexdigest' "$file"
  else
    echo "Error: need md5sum, md5, or ruby available to compute MD5." >&2
    exit 1
  fi
}

BUCKET="wb-data-public"
PREFIX="corkscrew"
APT_PREFIX="${PREFIX}/apt/debs"
APT_PUBLIC_KEY_KEY="${PREFIX}/apt/public.asc"

# Return remote ETag (lowercase, without quotes) for s3://$BUCKET/$key,
# or empty string if object does not exist.
get_remote_etag() {
  local key="$1"
  local etag=""
  # Avoid exiting on 404 under set -e
  set +e
  etag=$(aws s3api head-object \
    --bucket "$BUCKET" \
    --key "$key" \
    --query ETag \
    --output text 2>/dev/null)
  local status=$?
  set -e
  if [ $status -ne 0 ] || [ "$etag" = "None" ]; then
    echo ""
    return 0
  fi
  echo "$etag" | tr -d '"' | tr '[:upper:]' '[:lower:]'
}

# Upload tar.gz artifacts in packaging/
shopt -s nullglob
artifacts=( "$SELFDIR"/corkscrew-*.tar.gz )

echo "Uploading tar.gz artifacts to s3://$BUCKET/$PREFIX/"

for file in "${artifacts[@]}"; do
  basename=$(basename "$file")
  key="$PREFIX/$basename"

  local_md5=$(md5_of_file "$file")
  remote_etag=$(get_remote_etag "$key")

  # Determine whether this is a LATEST artifact
  is_latest=false
  if [[ "$basename" == *LATEST* ]]; then
    is_latest=true
  fi

  if [ -n "$remote_etag" ]; then
    if [ "$is_latest" = true ]; then
      if [ "$remote_etag" = "$local_md5" ]; then
        echo "Skipping $basename: remote matches local (ETag=$remote_etag)"
        continue
      fi
      if [ "$DRY_RUN" = true ]; then
        echo "Overwriting $basename: existing LATEST object at s3://$BUCKET/$key"
        continue
      fi
      echo "Overwriting $basename: existing LATEST object at s3://$BUCKET/$key ..."
    else
      echo "Skipping $basename: remote exists and artifact is versioned (not overwriting)"
      continue
    fi
  else
    if [ "$DRY_RUN" = true ]; then
      echo "Uploading $basename: new object to s3://$BUCKET/$key"
      continue
    fi
    echo "Uploading $basename: new object to s3://$BUCKET/$key ..."
  fi

  # Use s3api put-object to ensure single-part upload so ETag==MD5
  aws s3api put-object \
    --bucket "$BUCKET" \
    --key "$key" \
    --body "$file" \
    --acl public-read \
    --content-type application/gzip >/dev/null

  # Verify upload by checking ETag again
  new_etag=$(get_remote_etag "$key")
  if [ "$new_etag" = "$local_md5" ]; then
    echo "  Uploaded OK (ETag=$new_etag)"
  else
    echo "  Note: ETag after upload is $new_etag (expected MD5 $local_md5)" >&2
  fi
done

echo

# Flat APT repo upload (debs + Packages index + public key)
DEBS_DIR="$SELFDIR/debs"
GPG_PUBLIC_ASC="$SELFDIR/gpg/public.asc"

if [ -d "$DEBS_DIR" ]; then
  shopt -s nullglob
  debs=( "$DEBS_DIR"/*.deb )
  if [ ${#debs[@]} -eq 0 ]; then
    echo "No .deb files found in $DEBS_DIR; skipping APT publish"
  else
    echo "Uploading .deb files to s3://$BUCKET/$APT_PREFIX/"
    for deb in "${debs[@]}"; do
      basename=$(basename "$deb")
      key="$APT_PREFIX/$basename"
      key_dot="$APT_PREFIX/./$basename"
      local_md5=$(md5_of_file "$deb")
      remote_etag=$(get_remote_etag "$key")
      if [ -n "$remote_etag" ] && [ "$remote_etag" = "$local_md5" ]; then
        echo "Skipping $basename: remote matches local (ETag=$remote_etag)"
        if [ "$DRY_RUN" = false ]; then
          aws s3api put-object-acl --bucket "$BUCKET" --key "$key" --acl public-read >/dev/null || true
          remote_etag_dot=$(get_remote_etag "$key_dot")
          if [ -z "$remote_etag_dot" ]; then
            aws s3api put-object \
              --bucket "$BUCKET" \
              --key "$key_dot" \
              --body "$deb" \
              --acl public-read \
              --content-type application/vnd.debian.binary-package >/dev/null || true
          else
            aws s3api put-object-acl --bucket "$BUCKET" --key "$key_dot" --acl public-read >/dev/null || true
          fi
        fi
        continue
      fi
      if [ "$DRY_RUN" = true ]; then
        echo "Would upload $basename to s3://$BUCKET/$key and ./ variant"
      else
        echo "Uploading $basename to s3://$BUCKET/$key"
        aws s3api put-object \
          --bucket "$BUCKET" \
          --key "$key" \
          --body "$deb" \
          --acl public-read \
          --content-type application/vnd.debian.binary-package >/dev/null
        aws s3api put-object \
          --bucket "$BUCKET" \
          --key "$key_dot" \
          --body "$deb" \
          --acl public-read \
          --content-type application/vnd.debian.binary-package >/dev/null || true
      fi
    done

    # Upload Packages metadata files if present (also with literal './' path for APT)
    for index in Packages Packages.gz Release Release.gpg InRelease; do
      fpath="$DEBS_DIR/$index"
      if [ -f "$fpath" ]; then
        key="$APT_PREFIX/$index"
        key_dot="$APT_PREFIX/./$index"
        local_md5=$(md5_of_file "$fpath")
        remote_etag=$(get_remote_etag "$key")
        if [ -n "$remote_etag" ] && [ "$remote_etag" = "$local_md5" ]; then
          echo "Skipping $index: remote matches local (ETag=$remote_etag)"
          # Ensure both canonical and './' keys exist and are public
          if [ "$DRY_RUN" = false ]; then
            # Canonical key ACL
            aws s3api put-object-acl --bucket "$BUCKET" --key "$key" --acl public-read >/dev/null || true
            # Ensure './' variant exists; upload if missing
            remote_etag_dot=$(get_remote_etag "$key_dot")
            if [ -z "$remote_etag_dot" ]; then
              ctype="text/plain"
              [ "$index" = "Packages.gz" ] && ctype="application/gzip"
              [ "$index" = "Release.gpg" ] && ctype="application/pgp-signature"
              [ "$index" = "InRelease" ] && ctype="application/pgp-signature"
              aws s3api put-object \
                --bucket "$BUCKET" \
                --key "$key_dot" \
                --body "$fpath" \
                --acl public-read \
                --content-type "$ctype" >/dev/null || true
            else
              aws s3api put-object-acl --bucket "$BUCKET" --key "$key_dot" --acl public-read >/dev/null || true
            fi
          fi
          continue
        fi
        if [ "$DRY_RUN" = true ]; then
          echo "Would upload $index to s3://$BUCKET/$key"
        else
          ctype="text/plain"
          [ "$index" = "Packages.gz" ] && ctype="application/gzip"
          [ "$index" = "Release.gpg" ] && ctype="application/pgp-signature"
          [ "$index" = "InRelease" ] && ctype="application/pgp-signature"
          aws s3api put-object \
            --bucket "$BUCKET" \
            --key "$key" \
            --body "$fpath" \
            --acl public-read \
            --content-type "$ctype" >/dev/null
          aws s3api put-object \
            --bucket "$BUCKET" \
            --key "$key_dot" \
            --body "$fpath" \
            --acl public-read \
            --content-type "$ctype" >/dev/null || true
        fi
      fi
    done
  fi
else
  echo "Directory $DEBS_DIR does not exist; skipping APT publish"
fi

# Upload public GPG key for clients to install
if [ -f "$GPG_PUBLIC_ASC" ]; then
  key="$APT_PUBLIC_KEY_KEY"
  local_md5=$(md5_of_file "$GPG_PUBLIC_ASC")
  remote_etag=$(get_remote_etag "$key")
  if [ -n "$remote_etag" ] && [ "$remote_etag" = "$local_md5" ]; then
    echo "Skipping public.asc: remote matches local (ETag=$remote_etag)"
  else
    if [ "$DRY_RUN" = true ]; then
      echo "Would upload public key to s3://$BUCKET/$key"
    else
      aws s3api put-object \
        --bucket "$BUCKET" \
        --key "$key" \
        --body "$GPG_PUBLIC_ASC" \
        --acl public-read \
        --content-type text/plain >/dev/null
      echo "Uploaded public key to s3://$BUCKET/$key"
    fi
  fi
else
  echo "No public key found at $GPG_PUBLIC_ASC; skipping key upload"
fi

echo
echo "Done!"

